# Safelisting or Blocklisting Branches
branches:
  only:
  - feature/pwa-travis 

# Build Matrix (https://docs.travis-ci.com/user/build-matrix/)
matrix:
  include:
    - language: ruby
      rvm: 
        - 2.4.1
    - language: node_js

# ==============================================================
# Job lifecycle (https://docs.travis-ci.com/user/job-lifecycle/)
# ==============================================================
# 1. OPTIONAL Install apt addons
# 2. OPTIONAL Install cache components
# 3. before_install
before_install:
  # - sudo apt update
  - sudo apt-get install -y libcurl4-openssl-dev

# 4. install
install:
  - bundle install --path vendor/bundle
  - npm install --save workbox-cli

# 5. before_script
# before_script:
#  - chmod +x ./script/cibuild # or do this locally and commit

# 6. script
script: 
  - bundle exec jekyll build
  - workbox generateSW workbox-config.js 

# 7. OPTIONAL before_cache (for cleaning up cache)
# 8. after_success or after_failure
# 9. OPTIONAL before_deploy

# 10. OPTIONAL deploy
deploy:
  provider: pages
  target-branch: gh-pages
  keep-history: false
  fqdn: paesoe.org
  committer-from-gh: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: feature/pwa-travis

# 11. OPTIONAL after_deploy
# 12. after_script
# ==============================================================
# END OF JOB LIFECYCLE
# ==============================================================

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

cache: 
  - bundler # caching bundler gem packages will speed up build
  - npm
# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
