# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
permalink: /:year/:month/:day/:title

# Setup
title:               PAIESO
tagline:             'Emergency Surgery Saves Lives'
description:         'Professional Association of Integrated Emergency Surgery Officers of Ethiopia. Saving lives across Ethiopia through emergency obstetric, general and trauma surgery.'
url:                 'http://vvcb.github.io'
baseurl:             ''
paginate:            5 #This tells Jekyll how many posts to display per page

# About/contact
author:
  name:              vvcb
  url:               https://twitter.com/vvcb
  email:             emergencysurgery2000@gmail.com
  
# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Custom vars
version:             0.0.1
