# Site Setup
title: PAESOE-DEV
tagline: Testing Site
description: > 
  Professional Association of Emergency Surgery Officers in Ethiopia. 
  Saving lives across Ethiopia through emergency obstetric, general and trauma surgery.
url: https://vvcb.github.io
baseurl: '/paesoe-test'
version: 0.0.3
permalink: /:year/:month/:title

thumbnail: /assets/images/default-image.jpg

defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/images/default-image.jpg

# SEO
twitter:
  username: PaesoeOrg
  card: summary

facebook:
  publisher: https://www.facebook.com/Professional-association-of-Integrated-emergency-surgical-officers-912482102210807/

github:
  username: paesoe
  
social:
  name: PAESOE
  links:
    - https://twitter.com/PaesoeOrg
    - https://www.facebook.com/Professional-association-of-Integrated-emergency-surgical-officers-912482102210807/
    - https://www.linkedin.com/company/paesoe/
    - https://github.com/paesoe

webmaster_verifications:
  google: fvYLcEcUBoP2nUiuqZ5t4zkNH36vhQWdgRINHT7uF4Y
  bing: 304054A661DFFA8F74EA244BD262D2AC

# About/contact
author:
  name: vvcb
  url: https://github.com/vvcb
  email: ieso.ethiopia@gmail.com
  
# Jekyll Settings

sass:
  style: :compressed

# http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [li, p, td]
  ignore:
    envs: []
  blanklines: false
  # profile: true
  startings: []

markdown: kramdown
include: [_pages]
exclude: [_site, src, CHANGELOG.md, LICENSE, README.md, Gemfile, Gemfile.lock, 
          vendor, node_modules, package.json, package-lock.json, 
          webpack.config.js]

kramdown:
 parse_block_html: true
# Jekyll plugins
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

###############################################################
# Documentation
###############################################################

# https://help.github.com/articles/configuring-jekyll-plugins/
# Default Plugins
# - jekyll-coffeescript
# - jekyll-gist
# - jekyll-github-metadata
# - jekyll-paginate
# - jekyll-relative-links
# - jekyll-optional-front-matter
# - jekyll-readme-index
# - jekyll-default-layout
# - jekyll-titles-from-headings
# Optional Plugins
#  - jekyll-feed
#  - jekyll-redirect-from
#  - jekyll-seo-tag
#  - jekyll-sitemap
#  - jekyll-avatar
#  - jemoji
#  - jekyll-mentions
#  - jekyll-include-cache

# Default Jekyll Configuratiion Options
# https://jekyllrb.com/docs/configuration/default/

# # Where things are
# source              : .
# destination         : ./_site
# collections_dir     : .
# plugins_dir         : _plugins
# layouts_dir         : _layouts
# data_dir            : _data
# includes_dir        : _includes
# collections:
#   posts:
#     output          : true

# # Handling Reading
# safe                : false
# include             : [".htaccess"]
# exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
# keep_files          : [".git", ".svn"]
# encoding            : "utf-8"
# markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
# strict_front_matter : false

# # Filtering Content
# show_drafts         : null
# limit_posts         : 0
# future              : false
# unpublished         : false

# # Plugins
# whitelist           : []
# plugins             : []

# # Conversion
# markdown            : kramdown
# highlighter         : rouge
# lsi                 : false
# excerpt_separator   : "\n\n"
# incremental         : false

# # Serving
# detach              : false
# port                : 4000
# host                : 127.0.0.1
# baseurl             : "" # does not include hostname
# show_dir_listing    : false

# # Outputting
# permalink           : date
# paginate_path       : /page:num
# timezone            : null

# quiet               : false
# verbose             : false
# defaults            : []

# liquid:
#   error_mode        : warn
#   strict_filters    : false
#   strict_variables  : false

# # Markdown Processors
# rdiscount:
#   extensions        : []

# redcarpet:
#   extensions        : []

# kramdown:
#   auto_ids          : true
#   entity_output     : as_char
#   toc_levels        : 1..6
#   smart_quotes      : lsquo,rsquo,ldquo,rdquo
#   input             : GFM
#   hard_wrap         : false
#   footnote_nr       : 1
#   show_warnings     : false
